version: '3'
networks:
  codewrangle-proxy:
services:
  cw_website:
    image: docker.pkg.github.com/CodeWrangle/codewrangle/codewrangle_website:latest
    container_name: codewrangle_website
    ports:
      - '80:80'
      - '443:443'
    networks:
      - codewrangle-proxy
  watchtower:
    image: containrrr/watchtower
    container_name: codewrangle_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 300
    networks:
      - codewrangle-proxy
